language: python

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

env:
  global:
    - TWINE_USERNAME=__token__
    # Set TWINE_PASSWORD in Travis UI
    - CIBW_TEST_EXTRAS=test
    - CIBW_TEST_COMMAND="pytest {project}/tests"
    - CIBW_BUILD_VERBOSITY=1

jobs:
  include:
    - services: docker
      arch: arm64
    - services: docker
      arch: ppc64le
    - services: docker
      arch: s390x

install:
  - python3 -m pip install cibuildwheel==1.4.2 twine

script:
  - python3 -m cibuildwheel --output-dir wheelhouse
  - twine check wheelhouse/*

after_success:
  - |
    if [[ $TRAVIS_TAG ]]; then
      python3 -m twine upload wheelhouse/*.whl
    fi
