[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "numpy",
    "toml",
    "setuptools_scm>=4.1.2"
]

build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/boost_histogram/version.py"
