trigger:
  branches:
    include:
    - develop

variables:
  # This is the output name, - is replaced by _
  package_name: boost_histogram

jobs:

- job: LinuxSDist
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    python.architecture: 'none'
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7'
        architecture: 'x64'
    - script: |
        python -m pip install setuptools
        python setup.py sdist
      displayName: Publish sdist
    - script: |
        python -m pip install dist/*
      displayName: Verify pip source install
    - template: azure-publish-dist.yml

- job: LinuxCMake
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
        python.architecture: 'x64'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - template: azure-setup.yml
    - template: azure-cmake-steps.yml

- job: Wheels
  strategy:
    matrix:
      macOS_Python36:
        image: 'macOS-latest'
        python.version: '3.6'
        python.architecture: 'x64'
      Win_Python27_32:
        image: 'vs2017-win2016'
        python.version: '2.7'
        python.architecture: 'x86'
  pool:
    vmImage: $(image)
  steps:
    - template: azure-setup.yml
    - template: azure-steps.yml
    - template: azure-publish-dist.yml
