name: Tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
    - master
    - develop

jobs:
  pre-commit:
    name: Format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.0
    - name: Check manifest
      uses: pre-commit/action@v2.0.0
      with:
        extra_args: --hook-stage manual check-manifest

  cmake:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    name: CMake Python ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - uses: actions/setup-python@v2
      if: "!endswith(matrix.python-version, 'dev')"
      with:
        python-version: ${{ matrix.python-version }}
    - uses: deadsnakes/action@v1.0.0
      if: "endswith(matrix.python-version, 'dev')"
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install python tools
      run: python -m pip install -r dev-requirements.txt pytest-github-actions-annotate-failures

    - name: Configure
      run: mkdir -p build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Debug -DBOOST_HISTOGRAM_ERRORS=ON -DPYTHON_EXECUTABLE="$(which python)"

    - name: Build
      run: cmake --build build -j 2

    - name: Test
      working-directory: ./build
      run: python -m pytest
