name: Wheels

on: [push, pull_request]

env:
  CIBW_TEST_EXTRAS: test
  CIBW_TEST_COMAND: pytest {project}/tests
  CIBW_BUILD_VERBOSITY: 1


# todo: make an sdist, second job download abd publish

jobs:
  build_wheels:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - uses: actions/setup-python@v2
      name: Install Python
      with:
        python-version: '3.7'

    - name: Install cibuildwheel
      run: |
        python -m pip install cibuildwheel==1.4.1

    - name: Build wheel
      run: |
        python -m cibuildwheel --output-dir wheelhouse
      env:
        CIBW_SKIP: pp* cp27-win*
        
    - name: Show files
      run: ls -lh wheelhouse
      shell: bash

    - uses: actions/upload-artifact@v2
      with:
        path: wheelhouse/*.whl


  # Manylinux1 with workaround
  build_manylinux1_wheels:
    name: Build wheel on ManyLinux1
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - uses: actions/setup-python@v2
      name: Install Python
      with:
        python-version: '3.7'

    - name: Install cibuildwheel
      run: |
        python -m pip install cibuildwheel==1.4.1

    - name: Build wheel
      run: |
        python -m cibuildwheel --output-dir wheelhouse
      env:
        CIBW_BUILD: cp*manylinux_x86_64 cp*manylinux_i686
        CIBW_MANYLINUX_X86_64_IMAGE: skhep/manylinuxgcc-x86_64
        CIBW_MANYLINUX_I686_IMAGE: skhep/manylinuxgcc-i686
        
    - name: Show files
      run: ls -lh wheelhouse
      shell: bash

    - uses: actions/upload-artifact@v2
      with:
        path: wheelhouse/*.whl

  # Windows 2.7 (requires PyBind11 workaround)
  build_win27_wheels:
    name: Build Windows 2.7 wheel
    runs-on: windows-latest
    strategy:
      fail-fast: false
    env:
      DISTUTILS_USE_SDK: 1
      MSSdk: 1

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - uses: actions/setup-python@v2
      name: Install Python
      with:
        python-version: '3.7'

    - name: Install cibuildwheel
      run: |
        python -m pip install git+https://github.com/joerick/cibuildwheel

    - name: Build 64 bit wheel
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
        python -m cibuildwheel --output-dir wheelhouse
      shell: cmd
      env:
        CIBW_BUILD: cp27-win_amd64

    - name: Build 32 bit wheel
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86
        python -m cibuildwheel --output-dir wheelhouse
      shell: cmd
      env:
        CIBW_BUILD: cp27-win32
        
    - name: Show files
      run: ls -lh wheelhouse
      shell: bash

    - uses: actions/upload-artifact@v2
      with:
        path: wheelhouse/*.whl
